broker/urls.py
from django.urls import path, include
from django.views.generic import TemplateView, ListView

from . import views

urlpatterns = [
    path('', views.index, name="brokers"),
    path('ajouter/', views.ajouter, name="ajouter_broker"),
    path('modifier/<int:pk>', views.modifier, name="modifier_broker"),
    path('supprimer/<int:pk>', views.supprimer, name="supprimer_broker"),
]

dashmed_heroku/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from dashmed_heroku import settings
from dashmed_heroku._views import home

admin.autodiscover()

urlpatterns = [
    # path('account/', include('django.contrib.auth.urls')),
    path('', home, name="home"),
    path('admin/', admin.site.urls),
    path('brokers/', include('broker.urls')),
    path('comptes/', include('compte.urls')),
    path('tradeurs/', include('tradeur.urls')),
    path('payements/', include('payement.urls')),
    path('exercices/', include('exercice.urls')),
    path('operations/', include('operation.urls')),
    path('commerciaux/', include('commerciaux.urls')),
    path('investisseurs/', include('investisseur.urls')),
    path('investissements/', include('investissement.urls')),
    path('accounts/', include('accounts.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "dashmed_heroku._views.handler404"

investissement/urls.py
from django.urls import path, include
from django.views.generic import TemplateView, ListView

from . import views

urlpatterns = [
    path('', views.index, name="investissements"),
    path('ajouter/', views.ajouter, name="ajouter_investissement"),
    path('modifier/<int:pk>', views.modifier, name="modifier_investissement"),
    path('supprimer/<int:pk>', views.supprimer, name="supprimer_investissement"),
]

investissement/models.py
from datetime import date, datetime

from django.contrib.auth.models import User
from django.db import models, transaction

from compte.models import Compte
from investissement.utils import incrementer_date
from investisseur.models import Investisseur

POURCENTAGE_BONUS = .05
POURCENTAGE_MENSUEL = .3
MONTH_LENGTH = 30
PACK_CHOICES = [
    ('1', 'Profit Mensuel'),
    ('2', 'Bloqué')
]

class Pack(models.Model):
    libelle = models.CharField(max_length=14)
    duree = models.PositiveSmallIntegerField()
    taux = models.DecimalField(max_digits=5, decimal_places=2, null=False)

    def __str__(self):
        return f"Pack 0{self.id} ({self.libelle})"

class Investissement(models.Model):
    investisseur = models.ForeignKey(Investisseur, related_name='investissements', on_delete=models.CASCADE)
    montant = models.DecimalField(max_digits=10, decimal_places=2)
    date_investissement = models.DateField(default=date.today)
    date_decompte = models.DateField(default=date.today)
    pack = models.ForeignKey(Pack, related_name='investissements', on_delete=models.DO_NOTHING)
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['date_decompte']

    def __str__(self):
        return f"investissement n° {self.id}"

    def supprimer_payements(self):
        from payement.models import Payement

        payements = Payement.objects.filter(investissement=self)
        for payement in payements:
            payement.delete()

    def generer_payements(self):
        from payement.models import Payement

        with transaction.atomic():
            base_date = self.date_decompte
            for i in range(self.pack.duree):

                if i + 1 == self.pack.duree:
                    montant_payement = float(self.montant) * 1.4
                else:
                    montant_payement = float(self.montant) * 0.4

                base_date = incrementer_date(base_date, 30)
                payement = Payement(
                    investissement=self,
                    date=base_date,
                    montant=montant_payement
                )

                payement.investissement = self
                payement.save()

    def is_finish(self):
        today = date.today()
        invest_end = incrementer_date(self.date_decompte, 30 * self.pack.duree)

        return today > invest_end

    def payement_courant(self):
        payement = self.payements.filter(status="NP").order_by('date').first()
        return payement

    def payements_termines(self):
        payements = self.payements.filter(status__in=("VR", "RE", "EC")).order_by('date')
        return payements

    def bonus(self):
        return float(self.montant) * POURCENTAGE_BONUS

    def pourcentage_rsi(self):
        return self.retour_sur_investissement() * 100 / float(self.montant)

    def pourcentage(self):
        aujourdhui = date.today()

        if aujourdhui >= self.date_fin():
            return 100

        return int((aujourdhui - self.date_decompte).days * 100 / float(MONTH_LENGTH * self.pack.duree))

    def retour_sur_investissement(self):
        return float(self.montant) * (1 + (POURCENTAGE_MENSUEL * self.pack.duree))

    def date_fin(self):
        return incrementer_date(self.date_decompte, MONTH_LENGTH * self.pack.duree)

    def rang(self):
        rank = 1
        investissements = self.__class__.objects.filter(investisseur=self.investisseur)

        for i in range(len(investissements)):
            if investissements[i].id == self.id:
                return i + 1
        return rank

investissement/forms.py
from django.forms import ModelForm, Select, NumberInput, DateInput, TextInput

from investisseur.models import Investisseur
from .models import Investissement

DUREE_CHOICES = [
    ('1', '1 Mois'),
    ('2', '2 Mois'),
    ('3', '3 Mois'),
    ('4', '4 Mois'),
    ('5', '5 Mois')
]

class InvestissementForm(ModelForm):
    class Meta:
        model = Investissement
        # fields = '__all__'
        exclude = ['duree', 'taux']

        widgets = {
            'date_decompte': DateInput(
                attrs={
                    'class': 'form-control',
                    'required': True,
                    'type': 'date'
                },
            ),
            'date_investissement': DateInput(
                attrs={
                    'class': 'form-control',
                    'required': True,
                    'type': 'date',
                },
            ),
            'montant': NumberInput(
                attrs={
                    'class': 'form-control',
                    'required': True,
                },
            ),
            'investisseur': Select(
                attrs={
                    'class': 'form-control',
                    'required': True,
                },
            ),
            'pack': Select(
                attrs={
                    'class': 'form-control',
                    'required': True,
                },
            ),
        }

    def clean(self):
        cleaned_data = super().clean()


class InvestissementForm2(ModelForm):
    class Meta:
        model = Investissement
        exclude = ['duree', 'taux']

        widgets = {
            'date_decompte': DateInput(
                attrs={
                    'class': 'form-control',
                    'required': True,
                    'type': 'date'
                },
            ),
            'date_investissement': DateInput(
                attrs={
                    'class': 'form-control',
                    'required': True,
                    'type': 'date',
                },
            ),
            'montant': NumberInput(
                attrs={
                    'class': 'form-control',
                    'required': True,
                    'disabled': False,
                },
            ),
            'investisseur': Select(
                attrs={
                    'class': 'form-control disabled',
                    'required': True,
                    # 'disabled': True,
                },
                choices=[]
            ),
            'pack': Select(
                attrs={
                    'class': 'form-control',
                    'required': True,
                },
            ),
        }

investissement/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.http import JsonResponse, Http404
from django.shortcuts import render, redirect, reverse

from investissement.forms import InvestissementForm, InvestissementForm2
from investissement.models import Investissement
from investisseur.models import Investisseur

from datetime import date


@login_required
@staff_member_required
def index(request):
    groups = request.user.groups.all()

    if request.user.is_superuser:
        investissements = Investissement.objects.all()
    elif groups[0].name == "caissier":
        investissements = Investissement.objects.filter(date_investissement=date.today())
    else:
        raise Http404(request)

    context = {
        "investissements": investissements
    }
    return render(request, 'investissement/index.html', context)

@login_required
@staff_member_required
@transaction.atomic
def ajouter(request, pk=None):
    form = InvestissementForm()
    if pk:
        form = InvestissementForm2(
            initial={
                'investisseur': Investisseur.objects.get(pk=pk),
            }
        )

    context = {
        'form': form,
    }
    if request.method == 'POST':
        form = InvestissementForm(request.POST)
        print(form.errors)
        if form.is_valid():
            investissement = form.save()

            # investissement.generer_payements()

            return redirect('investissements')

    return render(request, 'investissement/ajouter.html', context)


@login_required
@staff_member_required
@transaction.atomic
def modifier(request, pk):
    investissement = Investissement.objects.get(id=pk)
    form = InvestissementForm(
        initial={
            'investisseur': investissement.investisseur,
            'montant': investissement.montant,
            'date_investissement': investissement.date_investissement.strftime('%Y-%m-%d'),
            'date_decompte': investissement.date_decompte.strftime('%Y-%m-%d'),
            'duree': investissement.pack.duree,
        }
    )
    form.instance = investissement
    context = {
        'form': form,
        'investissement': investissement,
    }
    if request.method == 'POST':
        form = InvestissementForm(request.POST)
        form.instance = investissement
        print(form.errors)
        if form.is_valid():
            if form.has_changed():
                investissement = form.save()
                investissement.supprimer_payements()
                investissement.generer_payements()

                return redirect('investissements')

    return render(request, 'investissement/modifier.html', context)


@login_required
@staff_member_required
@transaction.atomic
def supprimer(request, pk):
    investissement = Investissement.objects.get(id=pk)

    if request.is_ajax():
        if request.method == "DELETE":
            investissement.delete()
            return JsonResponse({"success": True})
    else:
        if request.method == "POST":
            investissement.delete()
        return redirect('investissements')

investissement/templates/investissement/forms/ajouter.html
{% load static %}


<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-row">
        <div class="col">
            <div class="form-group">
                <label for="id_investisseur">
                    <strong>Investisseur</strong>
                </label>
                {{ form.investisseur }}
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label for="id_montant">
                    <strong>Montant(Fcfa)</strong>
                </label>
                {{ form.montant }}
            </div>
        </div>
    </div>
    <div class="form-row">
        <div class="col">
            <div class="form-group">
                <label for="id_date_investissement">
                    <strong>Date Investissement</strong>
                </label>
                {{ form.date_investissement }}
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label for="id_date_decompte">
                    <strong>Date du Décompte</strong>
                </label>
                {{ form.date_decompte }}
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label for="id_pack">
                    <strong>Pack</strong>
                </label>
                {{ form.pack }}
            </div>
        </div>
    </div>
    <div class="form-group">
        <button class="btn btn-primary btn-sm" type="submit">Ajouter</button>
    </div>
</form>

investissement/templates/investissement/forms/modifier.html
{% load static %}


<form id="modifier_form" action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-row">
        <div class="col">
            <div class="form-group">
                <label for="id_investisseur">
                    <strong>Investisseur</strong>
                </label>
                {{ form.investisseur }}
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label for="id_montant">
                    <strong>Montant(Fcfa)</strong>
                </label>
                {{ form.montant }}
            </div>
        </div>
    </div>
    <div class="form-row">
        <div class="col">
            <div class="form-group">
                <label for="id_date_investissement">
                    <strong>Date Investissement</strong>
                </label>
                {{ form.date_investissement }}
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label for="id_date_decompte">
                    <strong>Date du Décompte</strong>
                </label>
                {{ form.date_decompte }}
            </div>
        </div>
    </div>
    <div class="form-group">
        <button class="btn btn-primary btn-sm" type="submit"><i class="fas fa-save"></i>&nbsp;Enrégistrer</button>
        <button class="btn btn-danger btn-sm" type="button"
                value="{% url 'supprimer_investissement' pk=investissement.id %}"
                onclick="supprimerInvestissement(this.value);">

            <i class="fas fa-trash" ></i>&nbsp;Supprimer

        </button>
    </div>
</form>