broker/urls.py
from django.urls import path, include
from django.views.generic import TemplateView, ListView

from . import views

urlpatterns = [
    path('', views.index, name="brokers"),
    path('ajouter/', views.ajouter, name="ajouter_broker"),
    path('modifier/<int:pk>', views.modifier, name="modifier_broker"),
    path('supprimer/<int:pk>', views.supprimer, name="supprimer_broker"),
]

dashmed_heroku/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from dashmed_heroku import settings
from dashmed_heroku._views import home

admin.autodiscover()

urlpatterns = [
    # path('account/', include('django.contrib.auth.urls')),
    path('', home, name="home"),
    path('admin/', admin.site.urls),
    path('brokers/', include('broker.urls')),
    path('comptes/', include('compte.urls')),
    path('tradeurs/', include('tradeur.urls')),
    path('payements/', include('payement.urls')),
    path('exercices/', include('exercice.urls')),
    path('operations/', include('operation.urls')),
    path('commerciaux/', include('commerciaux.urls')),
    path('investisseurs/', include('investisseur.urls')),
    path('investissements/', include('investissement.urls')),
    path('accounts/', include('accounts.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "dashmed_heroku._views.handler404"

tradeur/urls.py
from django.urls import path, include
from django.views.generic import TemplateView, ListView

from . import views

urlpatterns = [
    path('', views.index, name="tradeurs"),
    path('ajouter/', views.ajouter, name="ajouter_tradeur"),
    path('profile/<int:pk>/', views.profile, name="profile_tradeur"),
    path('supprimer/<int:pk>/', views.supprimer, name="supprimer_tradeur"),
]

tradeur/models.py
from django.contrib.auth.models import User
from django.db import models


class Tradeur(User):
    telephone = models.CharField(max_length=20, unique=True)
    sexe = models.CharField(max_length=1)
    avatar = models.ImageField(upload_to="photos/", null=True, blank=True)

tradeur/forms.py
from django.forms import Form, TextInput, Select, FileInput, NumberInput, EmailInput, ModelForm

from tradeur.models import Tradeur

SEX_CHOICES = [
    ('M', 'Masculin'),
    ('F', 'Féminin')
]


class Personne(Form):
    pass


class TradeurForm(ModelForm):
    class Meta:
        model = Tradeur
        fields = ['first_name', 'last_name', 'email', 'telephone', 'sexe', 'avatar', 'username']

        widgets = {
            'first_name': TextInput(
                attrs={
                    'class': 'form-control names',
                    'required': True,
                    'placeholder': "John",
                },
            ),
            'last_name': TextInput(
                attrs={
                    'class': 'form-control names',
                    'required': True,
                    'placeholder': "Doe",
                },
            ),
            'email': EmailInput(
                attrs={
                    'class': "form-control",
                    'required': True,
                    'placeholder': "tradeur@exemple.com",
                }
            ),
            'telephone': NumberInput(
                attrs={
                    'class': "form-control",
                    'required': True,
                    'placeholder': "0022893780353",
                }
            ),
            'sexe': Select(
                attrs={
                    'class': "form-control",
                    'required': True,
                },
                choices=SEX_CHOICES
            ),
            'avatar': FileInput(
                attrs={
                    'class': "form-control",
                }
            ),
            'username': TextInput(
                attrs={
                    'class': 'form-control',
                    'required': True,
                    'placeholder': "ex : DoeJhon",
                    # 'disabled': 'disabled'
                },
            ),
        }

tradeur/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import Group
from django.db import transaction
from django.http import JsonResponse
from django.shortcuts import render, redirect
from password_generator import PasswordGenerator

from tradeur.forms import TradeurForm
from tradeur.models import Tradeur

pwo = PasswordGenerator()


def index(request):
    context = {
        "tradeurs": Tradeur.objects.all()
    }
    return render(request, 'tradeur/index.html', context)

@login_required
@staff_member_required
@transaction.atomic
def ajouter(request):
    form = TradeurForm()
    context = {'form': form}

    if request.method == 'POST':
        form = TradeurForm(request.POST, request.FILES)

        if form.is_valid():
            first_password = pwo.generate()
            tradeur = form.save()
            tradeur.password = make_password(first_password)
            tradeur.init_password = first_password

            try:
                tradeur_grp = Group.objects.get(name="tradeur")
                tradeur_grp.user_set.add(tradeur)
            except Group.DoesNotExist:
                pass

        return redirect('tradeurs')

    return render(request, 'tradeur/ajouter.html', context)


@login_required
@staff_member_required
@transaction.atomic
def profile(request, pk):
    tradeur = Tradeur.objects.get(id=pk)
    form = TradeurForm(
        initial={
            'first_name': tradeur.first_name,
            'last_name': tradeur.last_name,
            'username': tradeur.username,
            'email': tradeur.email,
            'telephone': tradeur.telephone,
            'sexe': tradeur.sexe,
            'avatar': tradeur.avatar
        }
    )
    context = {
        'form': form,
        'tradeur': tradeur,
    }
    if request.method == 'POST':
        form = TradeurForm(request.POST, request.FILES)

        print(form.errors)
        # if form.is_valid():
        if form.has_changed():
            print('has changed')
            tradeur.first_name = request.POST['first_name']
            tradeur.last_name = request.POST['last_name']
            tradeur.email = request.POST['email']
            tradeur.telephone = request.POST['telephone']
            tradeur.sexe = request.POST['sexe']
            if request.FILES.get('avatar'):
                tradeur.avatar = request.FILES.get('avatar')
            tradeur.save()
            return redirect('tradeurs')

    return render(request, 'tradeur/profile.html', context)


@login_required
@staff_member_required
@transaction.atomic
def supprimer(request, pk):
    tradeur = Tradeur.objects.get(id=pk)

    if request.is_ajax():
        if request.method == "DELETE":
            tradeur.delete()
            response = JsonResponse({"success": True})
            return response
    else:
        if request.method == "POST":
            tradeur.delete()
            return redirect('tradeurs')
        return redirect('tradeurs')

tradeur/templates/tradeur/forms/ajouter.html
{% load static %}


<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-row">
        <div class="col">
            <div class="form-group">
                <label for="id_nom">
                    <strong>Nom</strong>
                </label>
                {{ form.first_name }}
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label for="id_prenom">
                    <strong>Prénom</strong>
                </label>
                {{ form.last_name }}
            </div>
        </div>
        <div class="col d-none">
            <div class="form-group">
                <label for="id_avatar">
                    <strong>Avatar</strong>
                </label>
                {{ form.avatar }}
                {{ form.username }}
            </div>
        </div>
    </div>
    <div class="form-row">
        <div class="col">
            <div class="form-group">
                <label for="id_telephone">
                    <strong>Téléphone</strong>
                </label>
                {{ form.telephone }}
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label for="id_email">
                    <strong>Adresse Email</strong>
                </label>
                {{ form.email }}
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label for="id_sexe">
                    <strong>Sexe</strong>
                </label>
                {{ form.sexe }}
            </div>
        </div>
    </div>
    <div class="form-group">
        <button class="btn btn-primary btn-sm" type="submit">Ajouter</button>
    </div>
</form>

tradeur/templates/tradeur/forms/modifier.html
{% load static %}


<form id="modifier_form" action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-row">
        <div class="col">
            <div class="form-group">
                <label for="id_nom">
                    <strong>Nom</strong>
                </label>
                {{ form.first_name }}
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label for="id_prenom">
                    <strong>Prénom</strong>
                </label>
                {{ form.last_name }}
            </div>
        </div>
        <div class="col d-none">
            <div class="form-group">
                <label for="id_avatar">
                    <strong>Avatar</strong>
                </label>
                {{ form.avatar }}
                {{ form.username }}
            </div>
        </div>
    </div>
    <div class="form-row">
        <div class="col">
            <div class="form-group">
                <label for="id_telephone">
                    <strong>Téléphone</strong>
                </label>
                {{ form.telephone }}
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label for="id_email">
                    <strong>Adresse Email</strong>
                </label>
                {{ form.email }}
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label for="id_sexe">
                    <strong>Sexe</strong>
                </label>
                {{ form.sexe }}
            </div>
        </div>
    </div>
    <div class="form-group">
        <button class="btn btn-primary btn-sm" type="submit"><i class="fas fa-save"></i>&nbsp;Save</button>
        <button class="btn btn-danger btn-sm" type="button"
                value="{% url 'supprimer_tradeur' pk=tradeur.id %}"
                onclick="supprimerTradeur(this.value);">

            <i class="fas fa-trash" ></i>&nbsp;Delete

        </button>
    </div>
</form>