broker/urls.py
from django.urls import path, include
from django.views.generic import TemplateView, ListView

from . import views

urlpatterns = [
    path('', views.index, name="brokers"),
    path('ajouter/', views.ajouter, name="ajouter_broker"),
    path('modifier/<int:pk>', views.modifier, name="modifier_broker"),
    path('supprimer/<int:pk>', views.supprimer, name="supprimer_broker"),
]

compte/urls.py
from django.urls import path, include
from django.views.generic import TemplateView, ListView, ArchiveIndexView

from . import views

urlpatterns = [
    path('', views.index, name="comptes"),
    path('ajouter/', views.ajouter, name="ajouter_compte"),
    path('modifier/<int:pk>', views.modifier, name="modifier_compte"),
    path('supprimer/<int:pk>', views.supprimer, name="supprimer_compte"),
]

dashmed_heroku/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from dashmed_heroku import settings
from dashmed_heroku._views import home

admin.autodiscover()

urlpatterns = [
    # path('account/', include('django.contrib.auth.urls')),
    path('', home, name="home"),
    path('admin/', admin.site.urls),
    path('brokers/', include('broker.urls')),
    path('comptes/', include('compte.urls')),
    path('tradeurs/', include('tradeur.urls')),
    path('payements/', include('payement.urls')),
    path('exercices/', include('exercice.urls')),
    path('operations/', include('operation.urls')),
    path('commerciaux/', include('commerciaux.urls')),
    path('investisseurs/', include('investisseur.urls')),
    path('investissements/', include('investissement.urls')),
    path('accounts/', include('accounts.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "dashmed_heroku._views.handler404"

compte/models.py
import datetime

from django.db import models
from django.urls import reverse

from broker.models import Broker
from tradeur.models import Tradeur


class Compte(models.Model):
    num_compte = models.CharField(max_length=225, unique=True)
    tradeur = models.ForeignKey(Tradeur, related_name='comptes', null=True, blank=True, on_delete=models.DO_NOTHING)
    broker = models.ForeignKey(Broker, related_name='comptes', on_delete=models.DO_NOTHING)
    montant_investi = models.PositiveSmallIntegerField()
    date_creation = models.DateField(default=datetime.datetime.now)

    def get_absolute_url(self):
        return reverse('comptes', kwargs={'pk': self.pk})

    def __repr__(self):
        return f"{self.num_compte}"

    def __str__(self):
        return f"{self.broker} : {self.num_compte}"


class Mois(models.Model):
    numero = models.CharField(max_length=30)
    balance_debut = models.DateField()
    balance_courante = models.IntegerField()
    compte = models.ForeignKey('exercice.ExerciceCompte', related_name='mois', on_delete=models.CASCADE)

    def __repr__(self):
        return f"{self.numero}"

broker/forms.py
from django import forms
from django.forms import TextInput


class BrokerForm(forms.Form):
    libelle = forms.CharField(
        max_length=50,
        widget=TextInput(
            attrs={
                'class': 'form-control',
                'required': True,
                'placeholder': "ex: XM",
            },
        ),
    )
    site_web = forms.CharField(
        max_length=50,
        widget=TextInput(
            attrs={
                'class': 'form-control',
                'required': True,
                'placeholder': "www.xm.com",
            },
        ),
    )

compte/forms.py
from django import forms
from django.forms import TextInput, Select, NumberInput, DateInput

from compte.models import Compte
from tradeur.models import Tradeur


class CompteForm(forms.ModelForm):
    class Meta:
        model = Compte
        fields = ['num_compte', 'broker', 'tradeur', 'montant_investi', 'date_creation']

        widgets = {
            'num_compte': TextInput(
                attrs={
                    'class': 'form-control',
                    'required': True,
                    'placeholder': "XXXXX-XXXXX-XXXXX",
                },
            ),
            'tradeur': Select(
                attrs={
                    'class': 'form-control',
                    # 'required': False,
                },
                choices=[]#Tradeur.objects.all(),
            ),
            'broker': Select(
                attrs={
                    'class': 'form-control',
                    'required': True,
                },
                choices=[]#Tradeur.objects.all()
            ),
            'montant_investi': NumberInput(
                attrs={
                    'class': 'form-control',
                    'required': True,
                    'placeholder': "200000",
                }
            ),
            'date_creation': DateInput(
                attrs={
                    'class': 'form-control',
                    'required': False,
                    'type': 'date',
                }
            ),
        }

compte/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render, redirect

from compte.forms import CompteForm
from compte.models import Compte
from tradeur.models import Tradeur

@login_required
@staff_member_required
def index(request):
    context = {
        "comptes": Compte.objects.all()
    }
    return render(request, 'compte/index.html', context)

@login_required
@staff_member_required
def ajouter(request):
    form = CompteForm()
    context = {
        'form': form,
    }
    if request.method == 'POST':
        form = CompteForm(request.POST)
        print(form.errors)
        if form.is_valid():
            form.save()
            return redirect('comptes')

    return render(request, 'compte/ajouter.html', context)

@login_required
@staff_member_required
def modifier(request, pk):
    compte = Compte.objects.get(id=pk)
    form = CompteForm(
        initial={
            'num_compte': compte.num_compte,
            'tradeur': compte.tradeur,
            'broker': compte.broker,
            'montant_investi': compte.montant_investi,
            'date_creation': compte.date_creation,
        }
    )
    form.instance = compte
    context = {
        'form': form,
        'compte': compte,
    }
    if request.method == 'POST':
        form = CompteForm(request.POST)
        form.instance = compte
        print(form.errors)
        if form.is_valid():
            if form.has_changed():
                form.save()
                return redirect('comptes')

    return render(request, 'compte/modifier.html', context)

@login_required
@staff_member_required
def supprimer(request, pk):
    compte = Compte.objects.get(id=pk)

    if request.is_ajax():
        if request.method == "DELETE":
            compte.delete()
            return JsonResponse({"success": True})
    else:
        if request.method == "POST":
            compte.delete()
            return redirect('comptes')
        return redirect('comptes')

compte/templates/compte/forms/ajouter.html
{% load static %}


<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-row">
        <div class="col">
            <div class="form-group">
                <label for="id_lebelle">
                    <strong>Identifiant du compte</strong>
                </label>
                {{ form.num_compte }}
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label for="id_site_web">
                    <strong>Broker</strong>
                </label>
                {{ form.broker }}
            </div>
        </div>
    </div>
    <div class="form-row">
        <div class="col">
            <div class="form-group">
                <label for="id_lebelle">
                    <strong>Tradeur</strong>
                </label>
                {{ form.tradeur }}
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label for="id_site_web">
                    <strong>Montant Investi</strong>
                </label>
                {{ form.montant_investi }}
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label for="id_date_creation">
                    <strong>Date de création</strong>
                </label>
                {{ form.date_creation }}
            </div>
        </div>
    </div>
    <div class="form-group">
        <button class="btn btn-primary btn-sm" type="submit">Ajouter</button>
    </div>
</form>

compte/templates/compte/forms/modifier.html
{% load static %}


<form id="modifier_form" action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-row">
        <div class="col">
            <div class="form-group">
                <label for="id_lebelle">
                    <strong>Identifiant du compte</strong>
                </label>
                {{ form.num_compte }}
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label for="id_site_web">
                    <strong>Broker</strong>
                </label>
                {{ form.broker }}
            </div>
        </div>
    </div>
    <div class="form-row">
        <div class="col">
            <div class="form-group">
                <label for="id_lebelle">
                    <strong>Tradeur</strong>
                </label>
                {{ form.tradeur }}
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label for="id_site_web">
                    <strong>Montant Investi</strong>
                </label>
                {{ form.montant_investi }}
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label for="id_date_creation">
                    <strong>Date de création</strong>
                </label>
                {{ form.date_creation }}
            </div>
        </div>
    </div>
    <div class="form-group">
        <button class="btn btn-primary btn-sm" type="submit"><i class="fas fa-save"></i>&nbsp;Save</button>
        <button class="btn btn-danger btn-sm" type="button"
                value="{% url 'supprimer_compte' pk=compte.id %}"
                onclick="supprimerCompte(this.value);">

            <i class="fas fa-trash" ></i>&nbsp;Delete

        </button>
    </div>
</form>